spring.application.name=bdgka_app
spring.artemis.embedded.data-directory=target/artemis/data
server.port=9000
spring.artemis.mode=embedded
spring.artemis.embedded.enabled=true
spring.artemis.host=localhost
spring.artemis.port=61616
spring.jms.pub-sub-domain=true
spring.jms.listener.acknowledge-mode=auto
# logging.level.org.apache.activemq.artemis=DEBUG
# logging.level.org.springframework.jms=DEBUG
spring.artemis.embedded.persistent=false
